package com.myrecipick.domain.user;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;


@DynamoDBTable(tableName = "user")
@Getter
@Setter
public class User {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    private UUID id;
    private String pUUID;
}
